version: "3.7"
services:
  dind-supercronic:
    image: hongkongkiwi/dind-supercronic:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_COMPOSE_ARCH: x86_64
        SUPERCRONIC_ARCH: amd64
        LANG: en_US.UTF-8
